### ISSUE TITLE
EventListener.js: Potential Incompatibility with Google Maps Events

### ISSUE THREAD

**Issue by barberboy** [akinuri/js-lib#2]
I have a customer who is using the Newspaper Pro Wordpress theme by TagDiv (https://demo.tagdiv.com/newspaper_pro/). They have include a modified version of your EventListener.js file. which causes click events on the Google Map to not be triggered/handled correctly. 

**_Note: This is fixed now on the customer site._**

Steps to Reproduce _(now obsolete)_:
1. Visit https://victoriamarket.ca/neighbourhoods/city-of-victoria 
2. Scroll down to the Victoria Map
3. Click on the cluster icons or the labels with prices

Expected Results:
The map should zoom when a cluster icon (number) is clicked.
A property card should pop up when the price label is clicked.

Actual Results:
Nothing happens when the map icons are clicked.

From what I can tell, the issue seems to be that the Google Maps event library is sometimes passing `undefined` as a value for the `options`/`useCapture` value (the third function parameter). This should have the same effect as the value not being provided, but because the `switch` statement on line 22 doesn't handle the value `'undefined'`, it falls through, and `nativeEventListenerAdder.call` is never called.

**Comment by akinuri** [comment]
This is the second issue related to tagDiv. I can see the use of this script in the demo site by searching `EventListeners` in the source code of the page, but I could not find any reference to it in the page you linked. I've seached for keywords from this script in the source code of the page and the loaded scripts, but found no matches. So, are you sure it's using `EventListener.js`?

Also, when I checked the page you linked, the map worked fine. I could see the popups and the zoom-in effect. So this might also be a browser issue. I tested this on Chrome 91.0.4472.77.

Converting the `switch` into an `if` and treating `undefined` as `false` might be a smart choice here, and even though I'm inclined to do that, I'd still like to get more info about the problem at hand. So

1. What was the browser you used to produce the problem? Does it occur on all browsers? The problem might be browser specific.
2. How do I make sure that the page/site you linked is actually using `EventListener.js`? I searched for `EventListeners`, `parseArgs`, `nativeEventListenerAdder`, but found none. The script might be obscured, but again, how to know?

**Comment by akinuri** [comment]
On second thought, there's a simpler check. On the demo site:

```
> window.addEventListener
ƒ () {
                var evtList = null;
                switch (arguments.length) {
                    // EventTarget.addEventListener(type, callback)
                    case 2:
                  …
> document.body.addEventListener
ƒ () {
                var evtList = null;
                switch (arguments.length) {
                    // EventTarget.addEventListener(type, callback)
                    case 2:
                  …
```
On the page you linked:

```
> window.addEventListener
ƒ (){arguments[0]=n(arguments[0]),e[t].originalFunctions.add.apply(t,arguments)}

> document.body.addEventListener
ƒ addEventListener() { [native code] }

> $0.addEventListener
ƒ addEventListener() { [native code] }
```
This suggest that the page you linked does not use `EventListener.js`. Also that `window.addEventListener` might be hijacked by some other script.

**Comment by barberboy** [comment]
Thank you so much for looking into this, @akinuri! I know these are weird bug reports to work on since you aren't in control of where/how people are using your code.

Turns out, after I filed this bug, the webmaster for victoriamarket.ca was able to remove the EventListener.js code from their site, so things are working correctly there now! The EventListener.js code is still on the demo page for the Newspaper theme, though, at https://demo.tagdiv.com/newspaper_pro/.

Essentially, this is a case that currently fails in Chrome 90.0.4430.212:

```js
var logClick = function(){ console.log('clicked!') }
var result = document.addEventListener('click', logClick, undefined)
console.log(result)
```

In this case, a 'click' listener _should be_ added to the document (with `useCapture` being `false`), and `result` should be the listener. This is not the case on their [demo page](https://demo.tagdiv.com/newspaper_pro/).

This scenario also fails:

```js
var logClick = function(){ console.log('clicked!') }
var result = document.addEventListener('click', logClick, undefined, false)
console.log(result)
```

I think your decision is correct to use `if` statements rather than a `switch` on the arguments length, and that `useCapture` should default to `false` if `undefined` is passed. Or you could set `useCapture` to `undefined` and pass that to the native `addEventListener`, which will have the same effect.

I appreciate you looking into this!

**Comment by akinuri** [comment]
Sure, no problem.

I thought about making a quick change to the script, but I think the current approach isn't right. I shouldn't be determining if the listener will be added or not. The listener should be added (pass the arguments to `nativeEventListenerAdder`) no matter what. The code should just log the listener/arguments. So, instead of making a quick change (using `if`s, etc.), will give it some thought, and modify/rewrite it later.

**Comment by barberboy** [comment]
Cool, yeah that makes sense. 

I haven't been able to tell from the source code what benefit this library is providing. Does it help with backwards-compatibility for `useCapture` being an object now instead of a boolean? At first I assumed it was shimming addEventListener for IE browsers, but then I saw that it uses those native methods under the hood anyway.

I apologize if that's a dumb or offensive question—I'm just trying to learn 😄

**Comment by akinuri** [comment]
I think I wrote this to use in a Chrome extension, or to use on some SPA site where I had no control over the page content. I'm not sure.

I needed a way to keep track of the events that are on the page. You can add event listeners, but there's no global container/object that keeps a record of all events on a page. If this script is run on a page before any event listeners are added, it logs all listeners along with their arguments.

This let's one search/filter event listeners, and maybe remove them. So, usually for debug purposes.

This is an old script, and I haven't used it recently. So I don't really remember :)

**Comment by barberboy** [comment]
Oh, sure! The `EventListeners` object has all the listeners there, to inspect, filter, remove, etc.... That makes sense.

Thanks!
